### PR TITLE
fix: Type check and downloadButton

### PR DESCRIPTION
**Pull request by Gimanh**
Fixed bug with typecheck in Vue3 and bug with download button.

### CODE REVIEW

**Comment by peshanghiwa** [comment]
@scholtz Please merge this PR

**Comment by Gimanh** [comment]
> @scholtz Please merge this PR

You can use my branch :) I'm waiting too long :)

**Comment by Gimanh** [comment]
> @scholtz Please merge this PR

You can use https://www.npmjs.com/package/qr-code-generator-vue3 
This package contains all fixes

**Comment by kbtomlinson** [comment]
I would also benefit from this being merged. Thank you.

**Comment by Gimanh** [comment]
> I would also benefit from this being merged. Thank you.

Here is last fixes. https://www.npmjs.com/package/qr-code-generator-vue3/v/1.4.21

**Pull request merged**
